# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SyncSocket
email: syncsocketdev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  True time synchronous messaging application server
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://syncsocket.github.io" # the base hostname & protocol for your site
twitter_username: sync_socket
github_username:  SyncSocket

# Build settings
markdown: kramdown

collections:
  docs:
    output: true
